### ISSUE TITLE
Pillar endpoint does not support lists

### ISSUE THREAD

**Issue by jgleissner** [kubic-project/velum#399]
The introduction of the pillar endpoint https://github.com/kubic-project/velum/pull/315 removes support for lists in pillar data, which used to be available through the external SQL pillar in salt master. For public cloud adaption, we want to store salt cloud specific data in the pillar, which requires a structure like this:
```
  profiles:
    cluster_node:
      block_device_mappings:
      - DeviceName: /dev/sda1
        Ebs.VolumeSize: 30
      image: ami-12345678
      network_interfaces:
      - AssociatePublicIpAddress: false
        DeviceIndex: 0
        SecurityGroupId: sg-1234abcd
        SubnetId: subnet-1234abcd
      provider: ec2
```
In this example, network_interfaces is an array consisting of one multi-key dictionary. It would be extremely helpful if structures like those could be served through the velum pillar.
